export * from './00-init'
export * from './01-enter-imei'
export * from './02-enter-memory-and-color'
export * from './10-pre-price-table'
export * from './20-upload-photo-process'
export * from './40-final-price-table'
export * from './50-contract'
